
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "8888:5432"
    volumes:
      - db_storage:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
    command: > 
      sh -c "python3 manage.py migrate && 
      gunicorn backend.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - media_storage:/backend/media
    depends_on:
      - db
      - nginx
  nginx:
    build:
      context: ./frontend
    ports:
      - 80:8080
    volumes:
      - media_storage:/backend/media
    depends_on:
      - db
volumes:
  db_storage:
  media_storage:
