
services:
  db:
    image: postgres:alpine
    env_file:
      - "postgresql.env"
    ports:
      - "8888:5432"
    volumes:
      - db_storage:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
    command: > 
      sh -c "python3 manage.py migrate && 
      gunicorn backend.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - media_storage:/backend/media
    env_file:
      - "django.env"
      - "postgresql.env"
    depends_on:
      - db
      - nginx
  nginx:
    build:
      context: ./frontend
    ports:
      - 80:8080
    volumes:
      - media_storage:/backend/media
    depends_on:
      - db
volumes:
  db_storage:
  media_storage:
